### ISSUE TITLE
Keep delay low not working with 1.1.0-web.3

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#10]
@Tester798 Hi again.  Twitch is testing new player versions again, the base one 1.0.1 works fine with keep delay low, but they are testing 1.1.0-web.3 and that version does NOT work with keep delay low.  The base version is at 50% in the experiments while the  Variant-a is also at 50%.  Hope it's just a quick fix not like that last time when they changed the version to a point it didn't work and you had to use a roundabout way of making it work that caused audio skipping.

Since the 1.0.1 is still at 50% see if you can include a way to function with either 1.0.1 or 1.1.0 so that all bases are covered.  I'll let you know if the ratio between base and variant-a changes in either direction.

**Comment by Tester798** [comment]
@thinkpad4 thanks for your report!
Tried to add a fix for it in 6.29. Let me know please if something isn't working as expected.

**Comment by Tester798** [comment]
Hmm, I tested a little this player (1.1.0-web.3-8bdaf638) and seems like it's not capable of low latency playback (<5 sec). When latency is coming to some critical value (~5sec and lower) then buffering is happening and latency goes back to higher value. Old player in separate window is playing stream (480p) in low latency (<3 sec) with no problem. Would be interesting to know where exactly this bug occurs and if it can be fixed somehow from FFZ side.

@thinkpad4 can you check please if you see similar behavior?

And on some streams it's fine, very strange...

**Comment by thinkpad4** [comment]
@Tester798 Knock on wood, everything seems to be working smooth, no issue with 1.1.0.  I have mine set to keep the delay sub 1 second on low latency streams and 3.5secs on Normal latency streams.  Fine so far
