### ISSUE TITLE
time of muted viewer

### ISSUE THREAD

**Issue by C44RL** [Tester798/ffzenhancing#13]
can you add a new thing to show how long the user has been muted in chat ? FFZ supported such function before but for some reason it hasnt been working for several months
old screenshot below
![unknown](https://user-images.githubusercontent.com/53061175/100550664-2e5f4700-3284-11eb-9147-1afff9625cd7.png)

**Comment by Tester798** [comment]
I think it's because twitch stopped providing this info for regular users (not mods).
Did you check if it's available somewhere?

**Comment by C44RL** [comment]
yes, i know some user who still sees the time and is not a mod. but i have no idea how he does it. (cant ask him unfortunately)

**Comment by Tester798** [comment]
Ok I checked ws messages and indeed there is timeout duration there. Not sure why FFZ stopped showing it. Need to research if it can be added back.

**Comment by C44RL** [comment]
thank you

**Comment by Tester798** [comment]
Ok was able to find the line which turns it off:
https://github.com/FrankerFaceZ/FrankerFaceZ/blob/7adee6556cd7962513c09f3d1cb1a693cdd58ccf/src/sites/twitch-twilight/modules/chat/index.js#L1496
If you delete that `false` in the line, then timeout time starts to show again.
Seems like the line was changed in
https://github.com/FrankerFaceZ/FrankerFaceZ/commit/fd2977f8999f0bd39211a5095f52adbf8310929c#diff-a7b9f3d73aa94e25e5af21d4799da0f8994114e53545a76d478ba0d3b9d82547L1410
not sure why.
Probably it's better to ask in FFZ repo.

**Comment by C44RL** [comment]
found an answer from ffz dev:
![Discord_YgqX6px8Go](https://user-images.githubusercontent.com/53061175/100554801-d1718a00-329f-11eb-860e-69a71a5dbc6e.png)

**Comment by C44RL** [comment]
sry but im not a developer. can i fix it myself somehow ? instead of waiting for a fix

**Comment by Tester798** [comment]
You can load extension from your machine like described here: https://github.com/FrankerFaceZ/FrankerFaceZ/blob/master/README.md
In this case you will need to keep web server running to serve script to your browser.
Also you can probably build the script and upload it somewhere and then use userscript https://cdn.frankerfacez.com/static/ffz_injector.user.js from your browser to load that code instead of original FFZ.
It's not very convenient so I would probably wait for the fix from FFZ.

**Comment by C44RL** [comment]
thanks for the help !

**Comment by Tester798** [comment]
Was playing with it for a little and looks like was able to make it show timeout time again using some disabled FFZ code.
Not sure if it will cause any bugs though, so please report if you see any unusual behavior.

**Comment by C44RL** [comment]
oh thank you so much! i'll test it soon

**Comment by C44RL** [comment]
seems like it works! great, thx
