### ISSUE TITLE
Add-on not working

### ISSUE THREAD

**Issue by sheep1n** [Tester798/ffzenhancing#14]
Hi, up until recently (I'd say the past few days) the add-on has stopped working for me on Opera. I've tried uninstalling both FFZ and the add-on but it doesn't fix it. I even uninstalled and reinstalled on Chrome and that seems to work but for whatever reason the add-on doesn't work in Opera for me right now.

**Comment by Tester798** [comment]
@sheep1n hi, thanks for the report.
Do you see add-on in FFZ?
Can you check if there are some errors in browser's developer tools console?
I will try to install Opera and check what is wrong there.

**Comment by sheep1n** [comment]
No, it doesn't appear under the add-ons section on FFZ. When I searched up FFZ on the console there's 2 warnings and 1 error that show up http://prntscr.com/vvy7on

**Comment by Tester798** [comment]
Yeah, that's indeed recent change. Will need to look up why it doesn't work in Opera.

**Comment by Tester798** [comment]
Not sure why but I didn't see the error when tested it in Opera.
Anyway, tried to replace `__lookupGetter__` with other code in 6.46.
Let me know please if it's fixed now for you.

**Comment by sheep1n** [comment]
Yes works perfectly now thank you so much!
