### ISSUE TITLE
None of the options seems to be keeping their function after a refresh even though they are still checked in the settings

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#15]
@Tester798 Version 6.46 I have Move "Users in Chat" Button to Bottom checked and when I refresh the page the users in chat thing is back to the default top even when it's still checked in settings.  This is happening on both the latest Chrome and FF versions

**Comment by thinkpad4** [comment]
Scratch that is seems NONE of the settings are sticking and I'm scared to touch the reduce delay setting cause that is working it seems

**Comment by thinkpad4** [comment]
More things broken, when I try to reenable Auto Reload on Video Freeze for the time being no stream will stay paused, they ALL will unpause after the default 4 sec wait time.  I say things need to be reverted to 6.43

**Comment by Tester798** [comment]
Thanks for your report.
Do you see any errors in browser's developer tools console window?
Also please do export your settings from FFZ and share them (check if there isn't any personal information) so I can import them into clean browser and test with them, maybe there is some specific option that cause errors, I'm not sure.

**Comment by thinkpad4** [comment]
@Tester798 In Dev tools, I see this 

Uncaught (in promise) TypeError: Cannot read property 'bind' of undefined
    at setupHandlers (ffzenhancing.js:732)
    at FFZEnhancingAddOn.onEnable (ffzenhancing.js:1210)
    at module.js:270

And this

logging.js:106 FFZ [site.player]: Unable to install document visibility hook. TypeError: Cannot redefine property: hidden
    at Function.defineProperty (<anonymous>)
    at Player.installVisibilityHook (player.jsx:1011)
    at Player.onEnable (player.jsx:546)
    at module.js:270
invoke @ logging.js:106


And my settings, 

[ffz-settings.zip](https://github.com/Tester798/ffzenhancing/files/5647973/ffz-settings.zip)

**Comment by thinkpad4** [comment]
Side note, is there a way to load the older versions of FFZenhancing?  SO I can try and see at which version things went bad?

**Comment by Tester798** [comment]
Thanks!
I tested with your settings in latest chrome canary and in latest stable firefox and as previously wasn't able to see the error.
But in 6.47 I tried to add some code for prevent your errors from happening by skipping that functionality. So please let me know if you see them in 6.47+.



> Side note, is there a way to load the older versions of FFZenhancing? SO I can try and see at which version things went bad?

Sure, you can install some userscript add-on in your browser and then add there script from https://raw.githubusercontent.com/Tester798/ffzenhancing/438e2f5304884e0b1f095f72dbe155be24c7bd62/ffzenhancing.js for example and after changing some vars in it (like `__ffzenhancing_base_url`) it should work.

**Comment by thinkpad4** [comment]
@Tester798 Looks like it's working again.  The "users in chat" moves to the bottom like I have it set to do, and the video quality restores to what I had it set to it goes to 160p after browsing clips and clicking back to the live stream from the clip window.

Thank you very much.  I'll keep checking the other features I have selected to make sure they are working too, but things look promising.
