### ISSUE TITLE
Extension for Safari (as user script ?)

### ISSUE THREAD

**Issue by a-nassim** [Tester798/ffzenhancing#17]
Would it be possible to use ffzenhancing with Safari ?
I am able to use FFZ using their user script in my scripts manager (https://github.com/quoid/userscripts)

So I thought there could be a way to do the same with ffzenhancing

**Comment by a-nassim** [comment]
I figured that I could get it to work using the file [ffzenhancing.js](https://github.com/Tester798/ffzenhancing/blob/master/ffzenhancing.js) and replacing the variable `__ffzenhancing_base_url` with `'https://raw.githubusercontent.com/Tester798/ffzenhancing/master/'`

Did I forget anything or this should be enough ?

Thanks in advance

**Comment by Tester798** [comment]
Thanks for your suggestion!

Yes, that should be enough.

But I added userscript loader now (which uses the same code as browser extension) so you should be able to install it from the [web page](https://tester798.github.io/ffzenhancing/) with the click on a button.
Tested in Firefox with Tampermonkey and seems like it's working fine. Not sure if it will work in Safari.
Let me know please if it works for you.

**Comment by a-nassim** [comment]
Thanks a lot for your quick answer !

So far it seems to work flawlessly, I will let you know if I notice anything.
Thanks again
