### ISSUE TITLE
Keep delay low with audio compressor

### ISSUE THREAD

**Issue by a-nassim** [Tester798/ffzenhancing#19]
I noticed that when the audio compressor is turned on, the keep delay low functionality is not working anymore.
Even when you turn the compressor off, you don't get the functionality back unless you refresh the page.

Would it be possible to have them both working together ?

I am using Firefox 85.0 with FFZ 4.20.57 and ffzenhancing 6.53

**Comment by Tester798** [comment]
It looks like it's very old Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=966247 and https://bugzilla.mozilla.org/show_bug.cgi?id=1517199
So I don't think it can be fixed here.
