### ISSUE TITLE
The Keep Delay Low doesn't seem to be working on Chrome or Firefox

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#2]
@tester798  The Keep Delay Low doesn't seem to be working anymore on Chrome or on Firefox.  I think Twitch changed something in the last few days.  It seems to be related to the new Backend Version 2.22.1, I used FFZ to switch back to Backend Version 2.17.2 Keep Delay Low works perfect again.  In FFZ Experiments I switched Twilight Player Core NPM Distribution (Public) and (Staff) to Base which gave me version 2.17.2.   So Backend Version 2.22.1 breaks Keep Delay Low.  Hope that helps you narrow down the issue.

**Comment by Tester798** [comment]
Thanks for the report. It looks like twitch is now blocking changing video playback rate by directly setting `playbackRate` of video element. Will need to find other way of changing playback rate of the video.

**Comment by Tester798** [comment]
Should be fixed in https://github.com/Tester798/ffzenhancing/commit/144ccf65ab9629cec2a2286a4c1404f0ff2eaf08.
Let me know please if something breaks because of this or if it's still not working.

**Comment by thinkpad4** [comment]
@Tester798 Working on Chrome 32 and 64-bit but on the latest Firefox 64-bit it doesn't seem to be working.  It shows the little FastForward icon next to the delay but then switches back to the little speedometer icon, and it keeps switching back and forth  between them.  This also causes the audio to stutter.

**Comment by Tester798** [comment]
@thinkpad4 thanks again for the report. Moved the code to more appropriate place and also added fix from FFZ to disable Twitch's own delay remover. Let me know please if it still doesn't work for you.

**Comment by thinkpad4** [comment]
Working for me now on Chrome 32 and 64-bit AND Firefox 64-Bit.  Thank you @Tester798  I don't have Firefox 32-Bit installed so I can't test that one.

**Comment by Tester798** [comment]
Thanks for the tests!
