### ISSUE TITLE
Twitch changed things again but not a issue with the video delay

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#20]
@Tester798 Hello, Twitch changed things again today and while the reduce delay part of your extention is still working the option Move "Users in Chat" Button to Bottom is NOT working at the moment.  I don't know about the other settings just yet but the video delay reducer IS working perfect.

**Comment by Tester798** [comment]
Thanks for your report!
This should be fixed in 6.55 now.
Let me know please if any other functionality is broken after recent changes.

**Comment by thinkpad4** [comment]
Thanks for the quick fix @Tester798 , I'll keep a eye out for anything else broken
