### ISSUE TITLE
Firefox every few seconds it stops

### ISSUE THREAD

**Issue by HGGamers** [Tester798/ffzenhancing#21]
Hello the stream stops every few seconds with this addon enabled.
I use the latest Firefox Beta (89.0). I already tried to disable (Keep Video Delay Low, Rest Player after BIg Delay) but that does not help. What could be the Problem?

Here is a small Video:
https://www.youtube.com/watch?v=Lb-kqJBHaWE

**Comment by Tester798** [comment]
@HGGamers do you have "Player > Auto Check Player Quality" setting turned on? If so, does it help when you turn it off?

**Comment by HGGamers** [comment]
Yes it was on, and I turned it off, and it works fine now. Thx!

**Comment by Tester798** [comment]
Thanks for the info! Will try to find the way to fix it.

**Comment by HGGamers** [comment]
Thanks for fixing this so fast. Can confirm works perfectly now. 👍🏼
