### ISSUE TITLE
Double-Click Username to Reply function not working

### ISSUE THREAD

**Issue by qzmtch** [Tester798/ffzenhancing#23]
the function has not been working for several months

**Comment by Tester798** [comment]
It works for me. What browser you are using? Do you have other extensions like betterttv installed? As I remember I had some problems when I had betterttv installed.

**Comment by qzmtch** [comment]
I tried on two browsers, cent browser 4.3.9.248 (Chromium 86.0.4240.198) and firefox 98.0.1 bttv not installed, just checked again, on empty firefox, no extensions, only ffz and ffzenhancing, the doubleclick function does not work

**Comment by Tester798** [comment]
Just checked in latest firefox and it works for me there too. Have no idea why it doesn't work for you. Maybe check dev tools console for error messages.

**Comment by qzmtch** [comment]
Uncaught TypeError: Cannot read property 'value' of null
    at HTMLBodyElement.<anonymous> (ffzenhancing.js:1000)
(anonymous) @ ffzenhancing.js:1000

**Comment by qzmtch** [comment]
I tried it on a pure virtual machine, on pure chrome 99.0.4844.74, and doubleclick does not work either

**Comment by Tester798** [comment]
Just checked on clean chrome profile: installed ffz, installed ffzenhancing, enabled double click to reply option and everything works fine for me. So I have no idea why it doesn't work for you.
Maybe it's some twitch experiment, but it's strange that it doesn't work for you for several months already.

You can try to fix it yourself by debugging the code locally.
Also let me know if you will have more info on the issue.

**Comment by qzmtch** [comment]
then can you help?, how to add the code https://tester798.github.io/ffzenhancing/ffzenhancing.js as a userscript without downloading this code from the link from https://tester798.github.io/ffzenhancing? so that it is entirely in one file and not loaded from git

**Comment by Tester798** [comment]
You can read about it here: https://github.com/Tester798/ffzenhancing#developing ("Developing" paragraph at the bottom)
Basically you need to download files from the repository, set local storage variable and run the web server. Then the script should be loaded from the same folder where you run the web server. After all is working you can try to edit the code to fix it.

**Comment by Tester798** [comment]
Closing this for now. Let me know if you will have more info.

**Comment by qzmtch** [comment]
all my tests were unsuccessful, in all browsers and on different computers, this function does not work anywhere, and I don’t load any settings, I just login to my twitch account, and that’s it, so I won’t try anymore, while I use ffz, inserting a nickname in textarea [https://i.imgur.com/dSBPPFp.png](https://i.imgur.com/dSBPPFp.png)

**Comment by Tester798** [comment]
@qzmtch finally yesterday I got new chat input field (the one which shows emotes as images as they are being entered) and I have double-click broken now too. Finally I can try to fix it now.

**Comment by qzmtch** [comment]
yes, yes, I have had this field with a choice of emotes for 2 months already, and I immediately thought about it, but since I am not a programmer, I could not find the right solution, find the right selector or class (I don’t know what to hook on to everything worked correctly)

**Comment by Tester798** [comment]
Ok, it should be fixed in 6.75.
Thanks for the report!
