### ISSUE TITLE
Question not a issue.  Was this always supposed to work? Fixed: Do not increase playback speed if buffer is too small

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#24]
@Tester798 Hi, this is more a question than a issue but was the not increasing playback speed when buffer is too small always supposed to work and hasn't until now?  I have my Maximum Video Delay in Low Latency set to 1 second so I can get sub 1 second viewing to make chat interaction with the streamer quicker but now I set it to 0.8 seconds to get sub second delays sometimes.  The question is what changed that make you fix the not increasing playback speed with a small buffer when to me at least things were working fine.

Thank you very much

**Comment by Tester798** [comment]
Thanks for the question.
Not sure why but live video playback started to lag for me for some time now, probably twitch is changing something again. Was trying to find a solution for this and noticed that buffer can be lower than actual latency to broadcaster. So I added a line for using buffer instead of latency if it's lower. But it seems like this wasn't a good fix because buffer values are jumping back and forth so playback speed is jumping with it. Probably need to revert the change.

**Comment by thinkpad4** [comment]
Yeah I noticed the lagging recently too, I'm 100% convinced Twitch changed something.  If you need to revert the change because it isn't working like you think it should of I say revert it and see if there is another way to balance the buffer with the latency.

**Comment by thinkpad4** [comment]
@Tester798 I'm gonna say revert it.  I'm getting the jumping around too,

**Comment by Tester798** [comment]
Ok, reverted. Need to find another way of fixing the lags on some streams. Maybe it's some problem with streaming servers or something else, not sure. If you will have any ideas please let me know.

**Comment by Tester798** [comment]
@thinkpad4 I tried to change "Twilight Player Core NPM Distribution (Public)" experiment in FFZ to "base" and it looks like it helps with periodic lags:
![image](https://user-images.githubusercontent.com/8844478/163251819-a746ab88-49d9-4a16-bd5f-c1ee39ca2d17.png)
You can check if it was changed by checking video stats:
![image](https://user-images.githubusercontent.com/8844478/163252320-371ae882-132d-40e1-988f-e0272b454357.png)

Can you please check if this will help you with your lags?

**Comment by thinkpad4** [comment]
@Tester798 Yes it seems much more stable on Backend Version 1.7.0-twitch.2-rc.3.  I'll keep using 1.7.0 for as long as Twitch shows it which probability won't be very long but every lag free day helps.
