### ISSUE TITLE
Ability to send duplicate messages using hidden characters

### ISSUE THREAD

**Issue by pointydev** [Tester798/ffzenhancing#26]
Hey there,

Thought it'd be a good idea to post this suggestion here, considering I don't think it'd make mainline FFZ. I'd love to see an option to allow users to bypass the 30 second unique message check, possibly basing it off how [7TV v2 does it](https://github.com/SevenTV/Extension/blob/5e23cb336eec103ead7daf6df806584717fb2290/src/Sites/twitch.tv/Runtime/InputManager.tsx#L109-L121) using Unicode tag characters.

Thanks,
pointy

**Comment by Tester798** [comment]
Thanks for your suggestion. But I'm not really sure when it can be helpful. Also I'm not a fan of implementing functionality that is already present in other extensions.
