### ISSUE TITLE
"Auto Check Player Quality" option forcing streams to 720p

### ISSUE THREAD

**Issue by LabAviator** [Tester798/ffzenhancing#28]
I've started encountering this issue several weeks ago, but only now narrowed it down to being caused by the FFZ Enhancing Add-On.

There is a setting in the add-on labelled "Auto Check Player Quality" which at least on my end now is always forcing the stream down to 720p quality. Whenever I pick any higher quality it's switched back to 720p within the next second. It used to work flawlessly in the past, but as I've said I have had this issue for a while now before figuring out it was this option causing it all of a sudden.

**Comment by Tester798** [comment]
Thanks for your report!
Yes, with option "Auto Check Player Quality" enabled, changing player quality was partially broken sometimes. I tried to fix it in version 6.88. Let me know please if you still see any bugs with it.
