### ISSUE TITLE
Keep Video Delay Low - no longer works

### ISSUE THREAD

**Issue by FAQU2** [Tester798/ffzenhancing#3]
Keep Video Delay Low no longer works after the recent Twitch update.
Also, if this feature is left on despite not working, weird sound artifacts may occur.

**Comment by Tester798** [comment]
Duplicate of #2 ?
What extension version you are using and on which browser?

**Comment by FAQU2** [comment]
> Duplicate of #2 ?
> What extension version you are using and on which browser?

My bad. I didn't notice there was a closed thread on the same issue. 
I'm using Chrome with the 6.0 version of the extension.

**Comment by ROvidiu18** [comment]
Uninstalled and reinstalled the extension. 
Now everything works fine. 
Sorry for my stupid issue report.
