### ISSUE TITLE
Support for Twitch Popout Player

### ISSUE THREAD

**Issue by mepherion** [Tester798/ffzenhancing#31]
Does the **FFZ Enhancing addon** support the Twitch popout/embed player (example: https://player.twitch.tv/?autoplay=true&channel=twitch&muted=false&parent=twitch.tv&player=popout&volume=1) for things like keeping the video delay lower, auto reload on errors, etc.?

The normal FFZ extension does load on the Twitch popout player and displays reset button, showing uptime, etc.

**Comment by Tester798** [comment]
Thanks for your report!
I tried to fix few errors to make it work on popout player pages.
Let me know please if you will find something is not working as intended.

**Comment by mepherion** [comment]
Thanks!

I did a quick test with "Keep Video Delay Low" and "Maximum Video Delay", and it seems to be working. 
The other settings are hard to verify in a live setting
