### ISSUE TITLE
Keep Video Delay Low has broken again

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#4]
@Tester798 Twitch is experimenting with updated Backend Version | 1.0.0-rc.12 and I think that broke the Keep Video Delay Low again.  It is related to the new Backend Version like before.  
I used FFZ to switch back to Backend Version | 0.9.80 Keep Delay Low works perfect again. In FFZ Experiments I switched Twilight Player Core NPM Distribution (Public) to Base which gave me version 0.9.80. So Backend Version 1.0.0-rc.12 breaks Keep Delay Low.  Switch Twilight Player Core NPM Distribution (Public) in FFZ experiments to Varient-b if you want to test  Backend Version | 1.0.0-rc.12 to try to find a fix

**Comment by Tester798** [comment]
Thanks for the report. Tried to fix it in 6.23. Let me know please if it still doesn't work properly.

**Comment by thinkpad4** [comment]
@Tester798 It seems to be causing a lot of buffering, I checked the experiments and it looks like Twitch placed everyone back on 0.9.80 so maybe revert the change you made until they enable the experiment again.  For streams using normal latency it keeps turning enabling and disabling.  And it's causing audio to sound like it's skipping.  I would say revert to 6.22 until they start the experiment again.  Edit:  I forced it to 1.0.0-rc.12 in experments even though it's set to 0% of twitch users at the moment, and it is working smooth on 1.0.0-rc.12 but it seems twitch has put everyone back on 0.9.80 again and the changes you made in 6.23 are causing issues with 0.9.80.

**Comment by Tester798** [comment]
It was turning enabling and disabling for me too until I added that `mediaSinkManager` fix in 6.23, and after that it became normal again.
Are you on latest version of browsers specified [here](https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining)? Because looks like operator `?.` only works in latest browsers.
Anyway I replaced it with old method in 6.24, if it still doesn't work for you then you can try to debug it locally as described in other issue [here](https://github.com/Tester798/ffzenhancing/issues/5#issuecomment-622256287).

**Comment by thinkpad4** [comment]
Yeah I'm in FF 75 and Chrome 80/81.  Edit:  Working PERFECT again!   Thank you very much for the quick fix

**Comment by Tester798** [comment]
That's strange then. If 6.24 isn't working for you still then not sure what can be done except local debugging at your side.

**Comment by thinkpad4** [comment]
Well I did say that things worked perfect when I was on 1.0.0-rc.12 but then Twitch reverted back to 0.9.80 the issues appeared.

**Comment by Tester798** [comment]
I'm on `0.9.80` too at the moment but I don't see the issue when it keeps turning enabling and disabling and any problems with sound, so I'm not really sure what is wrong. Maybe some other twitch experiment, maybe something else...

**Comment by thinkpad4** [comment]
I will keep you informed if the issue crops up again and will try to remember the steps/actions that I took that caused it to crop up again, like does a reload of the channel fix it, pausing and unpausing the video fix it, things like that.  Or does the issue appear only on first load of the channel or after a stream lags and then tries to catch up.

**Comment by thinkpad4** [comment]
@Tester798 ok, Twitch seems to be starting the experment again but with backend version 1.0.1-rc.12 not 1.0.0-rc.12  and keep video delay low seems to be working great without going back to the changes you made in 6.23.  "Knock on wood"  Low Latency streams seem fine currently, normal latency streams seem to lag when they get closer to the seconds delay I have set which is 3 seconds.  But don't start changing things just yet, I reverted back to 0.9.80 and it is doing it for normal latency streams too so it might just be my connection right now.  I will keep you informed of any further changes I notice and if the issue I'm having with streams using normal latency on either the old backend version or the new one resolves itself

**Comment by thinkpad4** [comment]
AND they went back to 0.9.80 again, this new backend must really be screwed up

**Comment by thinkpad4** [comment]
@Tester798 Twitch is testing 0.9.81 and so far, knock on wood, things look good, no issues yet

**Comment by thinkpad4** [comment]
@Tester798 Twitch is now testing 0.9.82 and still working great

**Comment by thinkpad4** [comment]
@Tester798 All is still good and working perfect.  I'm on 0.9.871 which seems to be Variant-B.

**Comment by thinkpad4** [comment]
@Tester798 Checking in again, all has been rock solid, I'm currently on 1.0.0-beta-82d01608 and all is well.
