### ISSUE TITLE
Add-On doesn't seem to load/attach to FFZ anymore

### ISSUE THREAD

**Issue by Taizunz** [Tester798/ffzenhancing#5]
Title describes the issue. A quick look at the FFZ log also doesn't show any signs that it's currently attempting to load the Enhancing Add-On.

**Comment by Tester798** [comment]
I see it in my FFZ add-ons just fine, so this can be some issue on your side or maybe it's broken just for you on initialization for some reason. Anyway there is no way I can check what is wrong with it, so you can try to debug it manually by running local web server and executing
`localStorage.ffzenhancingDebugMode = 'true'`
in your browser's console and after refreshing the page it should be loaded from your local web server.
There is https://github.com/Tester798/ffzenhancing/blob/master/Caddyfile config file for https://caddyserver.com/ so you can use that if you don't want to configure web server manually.

**Comment by Taizunz** [comment]
I was trying to troubleshoot some stuff just now, and I noticed that the FFZ:EA version went from 6.23 to 6.24, and now it's loading all fine again. I never managed to dig any deeper into what was causing it on my end.

**Comment by Tester798** [comment]
I think it was because of `?.` operator and your old browser version, more info [here](https://github.com/Tester798/ffzenhancing/issues/4#issuecomment-622260884).
Thanks for your report and sorry for inconvenience 6.23 caused to you.

**Comment by Taizunz** [comment]
Ah, yes. I'm running a slightly older version of Chrome (on purpose).
Thank you for looking into this and finding a solution.
