### ISSUE TITLE
Issue with Video Delay with Plugin Active

### ISSUE THREAD

**Issue by cmd430** [Tester798/ffzenhancing#6]
When the plugin is active delay to broadcaster is significantly higher than with the plugin disabled

**Comment by Tester798** [comment]
Thanks for the report.
Do you have "Keep Video Delay Low" turned on or is it happening only when it's turned off?
Maybe you have values "Maximum Video Delay" or "Maximum Video Delay in Low Latency" set to higher numbers than needed?

**Comment by cmd430** [comment]
these are the settings im using: [Imgur](https://i.imgur.com/H4fAogk.png)

**Comment by cmd430** [comment]
also for a reference with the plugin active i have ~5.7s to broadcaster even after player reset/page reload with plugin disabled it drops to ~1.2s for same streamer

**Comment by Tester798** [comment]
Enable "Keep Video Delay Low" and adjust "Maximum Video Delay" and "Maximum Video Delay in Low Latency" values to your needs.
If you want to have ~1.2s delay and if the stream you are watching is in low latency mode then you should set "Maximum Video Delay in Low Latency" to about 1.5-2 sec. But if the value will be too low, then the stream can start lagging, so there is also a balance between low values and lags.
