### ISSUE TITLE
Keeps disappearing again

### ISSUE THREAD

**Issue by InTheDepths** [Tester798/ffzenhancing#7]
I keep having to redownload the addon everytime i want it to work, but once i close my browser and come back later; it will be gone again.  Tried doing what was suggested in the previous thread about this issue, and Firefox seems to be loading it, but it just doesn't seem to load on Twitch.

**Comment by Tester798** [comment]
Not sure what you really mean. Maybe it can be some problem with your Firefox installation. Also I don't remember any `previous thread` where we talked about this issue.

**Comment by InTheDepths** [comment]
If you look in the closed issues, someone has had this issue before, but his issue was because he had an outdated version.  Also, i mean i have to reinstall the addon everytime i want it to work with ffz, and it will only continue to work while i keep Twitch open on my browser.

**Comment by Tester798** [comment]
How do you install the add-on? Do you have any other browser add-ons installed?
If you see the add-on is getting removed or disabled on add-ons page in your browser for no reason then it might be something wrong with your browser. Try reinstalling it or using some nightly version from [here](https://www.mozilla.org/en-US/firefox/channel/desktop/) and check if it's working in it.

**Comment by InTheDepths** [comment]
I've been installing it directly through Github. The only other addon i have installed is FFZ. It was never being disabled, as Firefox would load it, it just wouldn't load on Twitch.  

After uninstalling and reinstalling Firefox; it seems to be good now.  Apparently Firefox must have changed something along with some of the updates how websites load certain plugins, i am not sure, but now it works and i feel like an idiot.  Thanks for the help. Something to keep noted if this happens in the future again.
