### ISSUE TITLE
error #3000

### ISSUE THREAD

**Issue by C44RL** [Tester798/ffzenhancing#8]
hi, why does autoreload thing only work with #2000 and #4000 errors but ignore #3000 ? it would be so helpful to reload every error
![unknown](https://user-images.githubusercontent.com/53061175/87864091-76806b80-c96c-11ea-905f-4d0237f2e729.png)

**Comment by Tester798** [comment]
Added error #3000 to the reload list in version 6.25.
Thanks for the report!

**Comment by C44RL** [comment]
hi again, can you add error #5000 also pls ?
![Безымянный](https://user-images.githubusercontent.com/53061175/89031803-e236e100-d33b-11ea-9142-b19c989b8e00.png)

**Comment by Tester798** [comment]
Thanks for your suggestion, added in 6.27.

**Comment by C44RL** [comment]
add #1000 too pls
![chrome_hu4obwuCKt](https://user-images.githubusercontent.com/53061175/93008127-ff391380-f579-11ea-8ddb-e7a3b7ceef23.png)

**Comment by Tester798** [comment]
@C44RL added. Thanks for the report.
