### ISSUE TITLE
Add-On had disappeared from ffz

### ISSUE THREAD

**Issue by Asagius** [Tester798/ffzenhancing#9]
Current version is 6.27, but in chrome store is 6.0, so I can't even update it

**Comment by Tester798** [comment]
Version in chrome store is just a loader, so 6.0 is fine. Make sure you have installed FFZ too.

**Comment by Asagius** [comment]
![image](https://user-images.githubusercontent.com/37080956/90276773-bef45180-de64-11ea-82d7-43e8e3d866bf.png)
![image](https://user-images.githubusercontent.com/37080956/90277103-46da5b80-de65-11ea-8585-09af99425d2b.png)

**Comment by Tester798** [comment]
What version of FFZ you have (bottom left corner)?

**Comment by Asagius** [comment]
4.20.30

**Comment by Tester798** [comment]
I have the same version. Tested in Chrome Canary and in my main browser (Chromium MS Edge) and all is working fine for me:
![image](https://user-images.githubusercontent.com/8844478/90280177-29ac8980-de73-11ea-90cd-0ca52cfe236e.png)

So I have no idea what is wrong with your setup and why it disappeared for you. Maybe check dev tools network page to see if the js is loading for you from https://tester798.github.io/ffzenhancing/ffzenhancing.js url. Also you can check dev tools console window to see maybe there are some errors that will give you the idea for what is wrong.

Let me know if you will find something that I can fix.

**Comment by Asagius** [comment]
![image](https://user-images.githubusercontent.com/37080956/90281517-fcf57380-de6c-11ea-878c-18a632432fe1.png)

**Comment by Asagius** [comment]
Looks like you can't fix it

**Comment by Asagius** [comment]
If I turn on VPN extension works

**Comment by Tester798** [comment]
It's nice that you was able to find the issue 👍
